=== Airell/nmedit/nomad/net.nmedit.nomad.core/data/MenuLayout.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<schema 
	targetNamespace="http://nmedit.sf.net/MenuLayout"
	xmlns="http://www.w3.org/2001/XMLSchema"
    xmlns:ml="http://nmedit.sf.net/MenuLayout">

<annotation>
    <documentation xml:lang="EN">
		Menu layout schema.
    </documentation>
</annotation>

<simpleType name="iconType">
  <restriction base="string">
    <enumeration value="enabledIcon"/>
    <enumeration value="disabledIcon"/>
  </restriction>
</simpleType>

<element name="icon">
  <complexType>
    <attribute name="type" type="ml:iconType" default="enabledIcon"/>
    <attribute name="src" type="anyURI" use="required" />
  </complexType>
</element>

<element name="entry">
  <complexType>
	<sequence>
      <element ref="ml:icon" minOccurs="0" maxOccurs="unbounded"/>
      <element ref="ml:layout" minOccurs="0" maxOccurs="1"/>
      <element ref="ml:entry"  minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
    <attribute name="entryPoint" type="NMTOKEN" />
    <attribute name="flat" type="boolean" default="false" />
  </complexType>
</element>

</schema>

=== Airell/nmedit/nomad/net.nmedit.nomad.core/src/example/menulayout/MenuLayout.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<entry entryPoint="MainWindow.menu"
	xmlns="http://nmedit.sf.net/MenuLayout"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../data/MenuLayout.xsd"
	xsi:schemaLocation="http://nmedit.sf.net/MenuLayout ../../data/MenuLayout.xsd">
	<entry entryPoint="file" >
		<entry entryPoint="new">
			<entry entryPoint="file" />
			<entry entryPoint="location" />
			<entry entryPoint="device" />
		</entry>
		<entry entryPoint="open" />
		<entry entryPoint="close" flat="true">
			<entry entryPoint="close" />
			<entry entryPoint="closeall" />
		</entry>
		<entry entryPoint="save" flat="true">
			<entry entryPoint="save" />
			<entry entryPoint="saveas" />
			<entry entryPoint="saveall" />
		</entry>
		<entry entryPoint="ie" flat="true">
			<entry entryPoint="import" />
			<entry entryPoint="export" />
		</entry>
		<entry entryPoint="properties" />
		<entry entryPoint="exit" />
	</entry>
	<entry entryPoint="locale">
		<entry entryPoint="switch" />
	</entry>
</entry>
