=== Airell/nmedit/nomad/src/data/xml/modules-definition-v10.dtd
<!--
	This file is part of Nomad.

    Nomad is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    Nomad is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Nomad; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
-->
<!-- ==========================================================================

PURPOSE:
	This DTD was developed to define the modules of the Nord Modular
	synthesizer and to represent their hierarchie.

FIXME:
	(1.0) - The substitutions have to be better integrated. For example on the
			oscillator the frequency value (and with that it's substitution)
			depends on the states of the frequency-display, coarse and fine.
			In this version of the DTD supports no substitutions that
    		have more than one variable.
	(1.0) - All possible substitution-names should be defined in this DTD
	(1.0) - Language-independend substitutions for the values of a parameter
			should be defined in this DTD (for example simple string-
			substitutions like (0='Off',1='On'))
	(1.0) - Substitutions now threaded as language-depended, as they must
			be calculated (for example the Oscillator's frequency) might be
			represented in the xml file as well.

			Perhaps such a definition could look like:
			<substitution name="example-transformation">
				<transform
					offset = "0"				# 0  	should be default
					factor = "1.0"				# 1.0	should be default
					praefix-string	= "x"		# ""	should be default
					suffix-string   = "[UNIT]"	# ""	should be default
				/>
			</substitution>

			and represent the transformation 
	
					t_ 			:(value:int) -> string	
					  o,f,p,s

			defined as

					string := 
						concatenate(
							praefix-string			,
							(value+offset)*factor	,
							suffix-string	
						)
	(1.0) - There could be an 'optional'-element containing optional information
			about a module.

			For example it could contain layout related definitions such as
			how elements should be grouped. For example
				- coarse - fine - frequency-display belong together
	            - in- or outputs often belong to an additional level-knob

			This would definately increase the development time required to
			generate custom themes. Simply because
				- grouped elements can automatically be positioned together
				- more user interface components can be generated automatically
				  for example grouped elements could be put into a groupbox.
				  Also text/icon-labels (where it is reasonable).

CHANGE HISTORY:
[Version 1.0]
	2005-11-16 Initial Version.
	
=========================================================================== -->




<!-- ====================================================================== -->
<!-- Useful entities for increased DTD readability -->
<!-- ====================================================================== -->

<!-- Used to define the type of either an 'input' or an 'output' connector. -->
<!ENTITY % connector-type
	"type		(audio|control|logic|slave)	#REQUIRED">




<!-- 
		the core attributes of a 'parameter' (also the 'custom' element)
		'min': 			The smallest possible value.
		       			If the attribute is missing it implies a zero value.

		'max': 			The largest possible value.

		'default':		The default value.
						If the attribute is missing it implies a zero value.

		-'bitcount':	Number of bits reserved for the value.
						(expected by the protocol)
-->
<!ENTITY % value.att
   "min			NMTOKEN		#IMPLIED
	max			NMTOKEN		#REQUIRED
	default		NMTOKEN		#IMPLIED">




<!-- boolean values -->
<!ENTITY % boolean
	"true|false">




<!--
		The id for 'module', 'parameter', 'custom', 'input', 'output'.
		The id's value is equivalent to the index of an element defined
		in the protocol.

		For example two inputs with indices 0 and 1 must have an id with
		the same values 0 and 1.
-->
<!ENTITY % index-id
	"id 		NMTOKEN 	#REQUIRED">




<!-- ====================================================================== -->
<!-- top level element -->
<!-- ====================================================================== -->

<!ELEMENT modules-definition (structure, modules)>




<!-- ====================================================================== -->
<!-- elements for structuring the modules

		The elements order is equivalent to their order in the xml file.
-->
<!-- ====================================================================== -->

<!-- defines the hierarchie of the modules -->
<!ELEMENT structure (group+)>




<!-- Corresponds to the tabs of the tab-bar (like I/O, Osc, LFO, ...). -->
<!ELEMENT group 	(section+)>
<!--	
		'name':			The full name of a tab-bar.
		'short-name':	The name displayed in a tab-bar.
						If the attribute is missing it's value is implied
						by the value of attribute 'name'.
-->
<!ATTLIST group
	name 		CDATA		#REQUIRED
	short-name 	CDATA		#IMPLIED
>




<!-- Corresponds to the grouping of the modules inside a tab-bar. -->
<!ELEMENT section (insert+)>




<!-- Inserts a module into a specific section of a group. -->
<!ELEMENT insert EMPTY>
<!--
		'module-id':	The id of a module.
						A module with the same id must be defined inside the
						'modules'-element.
-->
<!ATTLIST insert 
	module-id	NMTOKEN		#REQUIRED>




<!-- ====================================================================== -->
<!-- elements for defining the properties of a module -->
<!-- ====================================================================== -->

<!-- Flat list containing the definitions for each module. -->
<!ELEMENT modules (module+)>




<!-- defines a module -->
<!ELEMENT module (custom|input|output|parameter)*>
<!--
		'id' (%index-id;):
						A number that corresponds to a module.
	
		'cva-only':		This attribute is only used in the PolyAreaIn module.
						Its value is false by default.
						The attribute has only to be specified if it should
						have 'true' as value.
	
		'limit'			Defines a limit of how many times a module is
						available in one patch. Not specifying this attribute
						means that the number of this module is not limited.
-->
<!ATTLIST module
	%index-id;
	short-name 	CDATA		#REQUIRED
	cva-only 	(%boolean;) "false"
	limit 		NMTOKEN		#IMPLIED
	cycles 		NMTOKEN		#REQUIRED
	dyn-mem 	NMTOKEN		#REQUIRED
	height 		NMTOKEN		#REQUIRED
	prog-mem 	NMTOKEN		#REQUIRED
	x-mem 		NMTOKEN		#REQUIRED
	y-mem 		NMTOKEN		#REQUIRED
	zero-page 	NMTOKEN		#REQUIRED
>




<!-- input connector -->
<!ELEMENT input EMPTY>
<!ATTLIST input
	%index-id;
	name 		CDATA 		#REQUIRED
	%connector-type;
>




<!-- output connector -->
<!ELEMENT output EMPTY>
<!ATTLIST output
	%index-id;
	name 		CDATA 		#REQUIRED
	%connector-type;
>




<!-- parameter

	'use-substitution':	Contains an identifier for the substitution that
						should be used to give the formatted representation
						of the parameter's raw value.
	
						A missing 'use-substitution' attribute implies that
						the value itself is equal to it's substitution.
						This simply means that for example the number 5
						is substituted by the string "5"

-->
<!ELEMENT parameter EMPTY>
<!ATTLIST parameter
	%index-id;
	name 		CDATA 		#REQUIRED
	%value.att;
	bit-count 	NMTOKEN		#REQUIRED
	use-substitution CDATA	#IMPLIED
>




<!-- custom-parameter -->
<!ELEMENT custom EMPTY>
<!ATTLIST custom
	%index-id;
	name 		CDATA 		#REQUIRED
	%value.att;
>




<!-- ====================================================================== -->
<!-- End of DTD -->
<!-- ====================================================================== -->

=== Airell/nmedit/nomad/src/data/xml/modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE modules-definition SYSTEM "modules-definition-v10.dtd">
<modules-definition>
  <modules>
    <module id="1" short-name="Keyboard" limit="1" cycles="0.0" prog-mem="0.0" x-mem="0.0" y-mem="0.0" zero-page="3.0" dyn-mem="1.0" height="2" >
      <output id="0" name="Note" type="control" />
      <output id="1" name="gate" type="logic" />
      <output id="2" name="velocity on" type="control" />
      <output id="3" name="velocity off" type="control" />
    </module>
    <module id="2" short-name="AudioIn" cycles="2.2" prog-mem="1.0" x-mem="1.0" y-mem="1.0" zero-page="2.0" dyn-mem="1.0" height="2" >
      <output id="0" name="left" type="audio" />
      <output id="1" name="right" type="audio" />
    </module>
    <module id="3" short-name="4Output" cycles="2.0625" prog-mem="0.46875" x-mem="0.09375" y-mem="0.0" zero-page="0.0" dyn-mem="0.28125" height="3" >
      <input id="0" name="out 1" type="audio" />
      <input id="1" name="out 2" type="audio" />
      <input id="2" name="out 3" type="audio" />
      <input id="3" name="out 4" type="audio" />
      <parameter id="0" name="level" min="0" max="127" bit-count="7" />
    </module>
    <module id="4" short-name="2Output" cycles="1.40625" prog-mem="0.34375" x-mem="0.09375" y-mem="0.09375" zero-page="0.0" dyn-mem="0.375" height="3" >
      <input id="0" name="out left" type="audio" />
      <input id="1" name="out right" type="audio" />
      <parameter id="0" name="level" min="0" max="127" bit-count="7" />
      <parameter id="1" name="destination" min="0" max="2" bit-count="2" use-substitution="channel-select-out2" />
      <parameter id="2" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="5" short-name="1Output" cycles="1.28125" prog-mem="0.3125" x-mem="0.09375" y-mem="0.09375" zero-page="0.0" dyn-mem="0.375" height="3" >
      <input id="0" name="out" type="audio" />
      <parameter id="0" name="level" min="0" max="127" bit-count="7" />
      <parameter id="1" name="dest" min="0" max="5" bit-count="3" use-substitution="channel-select-out1" />
      <parameter id="2" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="7" short-name="OscA" cycles="10.8125" prog-mem="6.5625" x-mem="0.84375" y-mem="0.34375" zero-page="1.75" dyn-mem="0.375" height="6" >
      <input id="0" name="sync" type="audio" />
      <input id="1" name="FMA" type="audio" />
      <input id="2" name="pitch 1" type="audio" />
      <input id="3" name="pitch 2" type="audio" />
      <input id="4" name="pulse width mod" type="audio" />
      <output id="0" name="out" type="audio" />
      <output id="1" name="slv" type="slave" />
      <custom id="0" name="freq display units" min="0" max="1" />
      <parameter id="0" name="freq coarse" min="0" max="127" bit-count="7" default="64" use-substitution="note" />
      <parameter id="1" name="freq fine" min="0" max="127" bit-count="7" default="64" use-substitution="offset-64" />
      <parameter id="2" name="freq KBT" min="0" max="127" bit-count="7" default="64" use-substitution="freq-kbt" />
      <parameter id="3" name="Pulse width" min="0" max="127" bit-count="7" default="64" use-substitution="transform-pulse-width" />
      <parameter id="4" name="waveform" min="0" max="3" bit-count="2" use-substitution="oscillator-wave" />
      <parameter id="5" name="pitch mod 1" min="0" max="127" bit-count="7" />
      <parameter id="6" name="pitch mod 2" min="0" max="127" bit-count="7" />
      <parameter id="7" name="fma mod" min="0" max="127" bit-count="7" />
      <parameter id="8" name="PW mod" min="0" max="127" bit-count="7" />
      <parameter id="9" name="Mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="8" short-name="OscB" cycles="8.28125" prog-mem="6.25" x-mem="0.6875" y-mem="0.5" zero-page="1.75" dyn-mem="0.6875" height="6" >
      <input id="0" name="FMA" type="audio" />
      <input id="1" name="pitch 1" type="control" />
      <input id="2" name="pitch 2" type="control" />
      <input id="3" name="PW mod" type="control" />
      <output id="0" name="out" type="audio" />
      <output id="1" name="slv" type="slave" />
      <custom id="0" name="freq display units" min="0" max="1" />
      <parameter id="0" name="Freq coarse" min="0" max="127" bit-count="7" default="64" use-substitution="note" />
      <parameter id="1" name="Freq fine" min="0" max="127" bit-count="7" default="64" use-substitution="offset-64" />
      <parameter id="2" name="Freq KBT" min="0" max="127" bit-count="7" default="64" use-substitution="freq-kbt" />
      <parameter id="3" name="waveform" min="0" max="3" bit-count="2" use-substitution="oscillator-wave" />
      <parameter id="4" name="pitch mod 1" min="0" max="127" bit-count="7" />
      <parameter id="5" name="pitch mod 2" min="0" max="127" bit-count="7" />
      <parameter id="6" name="fma mod" min="0" max="127" bit-count="7" />
      <parameter id="7" name="PWidth" min="0" max="127" bit-count="7" />
      <parameter id="8" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="9" short-name="OscC" cycles="4.96875" prog-mem="1.09375" x-mem="0.5625" y-mem="0.09375" zero-page="1.75" dyn-mem="0.53125" height="4" >
      <input id="0" name="FMA" type="audio" />
      <input id="1" name="pitch" type="audio" />
      <input id="2" name="AM" type="audio" />
      <output id="0" name="out" type="audio" />
      <output id="1" name="slv" type="slave" />
      <custom id="0" name="freq display units" min="0" max="1" />
      <parameter id="0" name="pitch coarse" min="0" max="127" bit-count="7" default="64" use-substitution="note" />
      <parameter id="1" name="pitch fine" min="0" max="127" bit-count="7" default="64" use-substitution="offset-64" />
      <parameter id="2" name="pitch KBT" min="0" max="1" bit-count="1" default="1" use-substitution="off-on" />
      <parameter id="3" name="pitch mod amount" min="0" max="127" bit-count="7" />
      <parameter id="4" name="FMA" min="0" max="127" bit-count="7" />
      <parameter id="5" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="10" short-name="OscSlvB" cycles="7.125" prog-mem="2.15625" x-mem="0.21875" y-mem="0.34375" zero-page="0.875" dyn-mem="0.5" height="3" >
      <input id="0" name="mst" type="slave" />
      <input id="1" name="PWmod" type="audio" />
      <output id="0" name="out" type="audio" />
      <custom id="0" name="freq display units" min="0" max="2" />
      <parameter id="0" name="detune coarse" min="0" max="127" bit-count="7" default="64" />
      <parameter id="1" name="detune fine" min="0" max="127" bit-count="7" default="64" use-substitution="offset-64" />
      <parameter id="2" name="PW" min="0" max="127" bit-count="7" use-substitution="transform-pulse-width" />
      <parameter id="3" name="PW mod" min="0" max="127" bit-count="7"  default="64" />
      <parameter id="4" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="11" short-name="OscSlvC" cycles="6.0" prog-mem="1.75" x-mem="0.15625" y-mem="0.21875" zero-page="0.875" dyn-mem="0.5" height="3" >
      <input id="0" name="mst" type="slave" />
      <input id="1" name="FMA" type="audio" />
      <output id="0" name="out" type="audio" />
      <custom id="0" name="freq display units" min="0" max="2" />
      <parameter id="0" name="detune coarse" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="1" name="detune fine" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="2" name="FMA mod" min="0" max="127" bit-count="7" />
      <parameter id="3" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="12" short-name="OscSlvD" cycles="5.875" prog-mem="1.3125" x-mem="0.15625" y-mem="0.21875" zero-page="0.875" dyn-mem="0.4375" height="3" >
      <input id="0" name="mst" type="slave" />
      <input id="1" name="FMA" type="audio" />
      <output id="0" name="out" type="audio" />
      <custom id="0" name="freq display units" min="0" max="2" />
      <parameter id="0" name="detune coarse" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="1" name="detune fine" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="2" name="FMA mod" min="0" max="127" bit-count="7" />
      <parameter id="3" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="13" short-name="OscSlvE" cycles="3.0625" prog-mem="0.6875" x-mem="0.34375" y-mem="0.15625" zero-page="0.875" dyn-mem="0.4375" height="3" >
      <input id="0" name="mst" type="slave" />
      <input id="1" name="FMA" type="audio" />
      <input id="2" name="AM" type="audio" />
      <output id="0" name="out" type="audio" />
      <custom id="0" name="freq display units" min="0" max="2" />
      <parameter id="0" name="detune coarse" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="1" name="detune fine" min="0" max="127" bit-count="7" use-substitution="offset-64" />
      <parameter id="2" name="FMA mod" min="0" max="127" bit-count="7" />
      <parameter id="3" name="mute" min="0" max="1" bit-count="1" use-substitution="off-on" />
    </module>
    <module id="14" short-name="OscSlvA" cycles="7.625" prog-mem="5.875" x-mem="0.4375" y-mem="0.28125" zero-page="0.875" dyn-mem="0.5" height="4" >
      <input id="0" name="mst" type="slave" />
      <input id="1" name="FMA" type="audio" />
      <input id="2" name="sync" type="audio" />
      <input id="3" name="AM" type="audio" />
      <output id="0" name="out" type="audio" />
      <custom id="0" name="freq display units" min="0" max="2" />
