=== Airell/nmedit/nomad/src/data/xml/substitutions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated from substitutions.xml by XMLBuddy -->
<!ELEMENT if EMPTY>
<!ATTLIST if
	replace-with CDATA #REQUIRED
	value-is NMTOKEN #REQUIRED
>
<!ELEMENT item (#PCDATA)>
<!ELEMENT list (item+)>
<!ATTLIST list id ID #REQUIRED>
<!ELEMENT substitutions (transform+,use-implementation+,list+)>
<!ELEMENT transform (if?)>
<!ATTLIST transform
	factor NMTOKEN #IMPLIED
	id ID #REQUIRED
	offset NMTOKEN #IMPLIED
	praefix CDATA #IMPLIED
	suffix CDATA #IMPLIED
>
<!ELEMENT use-implementation EMPTY>
<!ATTLIST use-implementation
	class ID #REQUIRED
	id NMTOKEN #REQUIRED
>

=== Airell/nmedit/nomad/src/data/xml/substitutions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE substitutions SYSTEM "substitutions.dtd">
<substitutions>

<!--    <transform id="blabla" offset="0" factor="1" praefix="p" suffix="s">
        <if value-is="0" replace-with="Off" />
    </transform> -->

    <transform id="offset-64" offset="-64" />
    <transform id="offset-add-1" offset="1" />

    <transform id="offset-64-2" offset="-64">
        <if value-is="127" replace-with="64" />
    </transform>

    <transform id="timbre" offset="1" >
        <if value-is="127" replace-with="Rnd"/>
    </transform>
    <transform id="quantizer-bits" offset="1">
<!--        <if value="12" replace-with="Off"/> -->
    </transform>
    <transform id="compressor-treshold" offset="-30" suffix="dB">
        <if value-is="42" replace-with="Off"/>
    </transform>
    <transform id="expander-treshold" offset="-84" suffix="dB">
        <if value-is="84" replace-with="Off"/>
    </transform>
    <transform id="compressor-rev-level" offset="-30" suffix="dB" />
    <transform id="compressor-limiter" offset="-12" suffix="dB">
        <if value-is="24" replace-with="Off"/>
    </transform>
    <transform id="offset-24-db" offset="-24" suffix="dB" />
    <transform id="expander-gate" offset="-84" suffix="db">
        <if value-is="0" replace-with="Off"/>
    </transform>
    <transform id="expander-hold" factor="4" suffix="ms">
        <if value-is="0" replace-with="Off"/>
    </transform>
    <transform id="envelope-level-divider" factor="0.5">
        <if value-is="127" replace-with="64" />
    </transform>
    <transform id="note-range">
        <if value-is="0" replace-with="Off"/>
    </transform>
    <transform id="pattern-step" offset="1">
        <if value-is="0" replace-with="Off"/>
    </transform>
    <transform id="off-then-value">
        <if value-is="0" replace-with="Off"/>
    </transform>
    <transform id="velocity-scale-gain" offset="-24" suffix="dB" />
    <transform id="vocoder-band-range">
        <if value-is="0" replace-with="Off" />
    </transform>
    <transform id="freq-kbt" factor="0.015748031496062992" praefix="x">
        <if value-is="0" replace-with="Off" />
    </transform>
    <transform id="transform-pulse-width" offset="1" factor="0.77165354330708658" suffix="%" />

    <use-implementation id="amp-gain" class="nomad.model.descriptive.substitution.AmpGain" />
    <use-implementation id="bpm" class="nomad.model.descriptive.substitution.BPM" />
    <use-implementation id="digitizer-hz" class="nomad.model.descriptive.substitution.DigitizerHz" />
    <use-implementation id="drum-hz" class="nomad.model.descriptive.substitution.DrumHz" />
    <use-implementation id="drumpartials" class="nomad.model.descriptive.substitution.DrumPartials" />
    <use-implementation id="eq-hz" class="nomad.model.descriptive.substitution.EqHz" />
    <use-implementation id="filter-hz-1" class="nomad.model.descriptive.substitution.FilterHz1" />
    <use-implementation id="filter-hz-2" class="nomad.model.descriptive.substitution.FilterHz2" />
    <use-implementation id="lfo-hz" class="nomad.model.descriptive.substitution.LFOHz" />
    <use-implementation id="logic-delay" class="nomad.model.descriptive.substitution.LogicDelay" />
    <use-implementation id="note" class="nomad.model.descriptive.substitution.Note" />
    <use-implementation id="note-scale" class="nomad.model.descriptive.substitution.NoteScale" />
    <use-implementation id="osc-hz" class="nomad.model.descriptive.substitution.OscHz" />
    <use-implementation id="partial-range" class="nomad.model.descriptive.substitution.PartialRange" />
    <use-implementation id="partials" class="nomad.model.descriptive.substitution.Partials" />
    <use-implementation id="phase" class="nomad.model.descriptive.substitution.Phase" />
    <use-implementation id="semitones" class="nomad.model.descriptive.substitution.Semitones" />
    <use-implementation id="smooth-time" class="nomad.model.descriptive.substitution.SmoothTime" />

  <list id="channel-select-out1">
    <item>1</item>
    <item>2</item>
    <item>3</item>
    <item>4</item>
    <item>L</item>
    <item>R</item>
  </list>
  <list id="channel-select-out2">
    <item>1/2</item>
    <item>3/4</item>
    <item>CVA</item>
  </list>
  <list id="white-colored">
    <item>White</item>
    <item>Colored</item>
  </list>
  <list id="oscillator-wave">
    <item>Sine</item>
    <item>Tri</item>
    <item>Saw</item>
    <item>Square</item>
  </list>
  <list id="filter-type-3">
    <item>LP</item>
    <item>BP</item>
    <item>HP</item>
  </list>

  <list id="filter-type-4">
    <item>LP</item>
    <item>BP</item>
    <item>HP</item>
    <item>BR</item>
  </list>
  <list id="filter-slope-2">
    <item>12 dB/Oct</item>
    <item>24 dB/Oct</item>
  </list>
  <list id="filter-slope-3">
    <item>12 dB/Oct</item>
    <item>18 dB/Oct</item>
    <item>24 dB/Oct</item>
  </list>
  <list id="lfo-wave">
    <item>Sine</item>
    <item>Tri</item>
    <item>Saw</item>
    <item>Inverse saw</item>
    <item>Square</item>
  </list>
  <list id="lfo-range">
    <item>Sub</item>
    <item>Lo</item>
    <item>Hi</item>
  </list>
  <list id="envelope-adsr-shape">
    <item>Log</item>
    <item>Lin</item>
    <item>Exp</item>
  </list>
  <list id="envelope-multi-shape">
    <item>Bipolar</item>
    <item>Uni/Exp</item>
    <item>Uni/Lin</item>
  </list>
  <list id="odd-all">
    <item>Odd</item>
    <item>All</item>
  </list>
  <list id="low-high">
    <item>Low</item>
    <item>High</item>
  </list>
  <list id="off-on">
    <item>Off</item>
    <item>On</item>
  </list>
  <list id="logic-function">
    <item>And</item>
    <item>Or</item>
    <item>Xor</item>
  </list>
  <list id="diode-function">
    <item>Pass through</item>
    <item>Half wave rectifiy</item>
    <item>Full wave rectify</item>
  </list>
  <list id="level-function">
    <item>Pass through</item>
    <item>Shift down</item>
    <item>Shift up</item>
  </list>
  <list id="shape-function">
    <item>log 2</item>
    <item>log 1</item>
    <item>lin</item>
    <item>exp 1</item>
    <item>exp 2</item>
  </list>
  <list id="control-mixer-mode">
    <item>lin</item>
    <item>exp</item>
  </list>
  <list id="vowels">
    <item>A</item>
    <item>E</item>
    <item>I</item>
    <item>O</item>
    <item>U</item>
    <item>Y</item>
    <item>AA</item>
    <item>AE</item>
    <item>OE</item>
  </list>
  <list id="drum-presets">
    <item>none</item>
    <item>Kick 1</item>
    <item>Kick 2</item>
    <item>Kick 3</item>
    <item>Kick 4</item>
    <item>Kick 5</item>
    <item>Snare 1</item>
    <item>Snare 2</item>
    <item>Snare 3</item>
    <item>Snare 4</item>
    <item>Snare 5</item>
    <item>Tom1 1</item>
    <item>Tom1 2</item>
    <item>Tom1 3</item>
    <item>Tom2 1</item>
    <item>Tom2 2</item>
    <item>Tom2 3</item>
    <item>Tom3 1</item>
    <item>Tom3 2</item>
    <item>Tom3 3</item>
    <item>Cymb 1</item>
    <item>Cymb 2</item>
    <item>Cymb 3</item>
    <item>Cymb 4</item>
    <item>Cymb 5</item>
    <item>Perc 1</item>
    <item>Perc 2</item>
    <item>Perc 3</item>
    <item>Perc 4</item>
    <item>Perc 5</item>
    <item>Perc 6</item>
  </list>
  <list id="adsr-time">
    <item>0.5m</item>
    <item>0.7m</item>
    <item>1.0m</item>
    <item>1.3m</item>
    <item>1.5m</item>
    <item>1.8m</item>
    <item>2.1m</item>
    <item>2.3m</item>
    <item>2.6m</item>
    <item>2.9m</item>
    <item>3.2m</item>
    <item>3.5m</item>
    <item>3.9m</item>
    <item>4.2m</item>
    <item>4.6m</item>
    <item>4.9m</item>
    <item>5.3m</item>
    <item>5.7m</item>
    <item>6.1m</item>
    <item>6.6m</item>
    <item>7.0m</item>
    <item>7.5m</item>
    <item>8.0m</item>
    <item>8.5m</item>
    <item>9.1m</item>
    <item>9.7m</item>
    <item>10m</item>
    <item>11m</item>
    <item>12m</item>
    <item>13m</item>
    <item>13m</item>
    <item>14m</item>
    <item>15m</item>
    <item>16m</item>
    <item>17m</item>
    <item>19m</item>
    <item>20m</item>
    <item>21m</item>
    <item>23m</item>
    <item>24m</item>
    <item>26m</item>
    <item>28m</item>
    <item>30m</item>
    <item>32m</item>
    <item>35m</item>
    <item>37m</item>
    <item>40m</item>
    <item>43m</item>
    <item>47m</item>
    <item>51m</item>
    <item>55m</item>
    <item>59m</item>
    <item>64m</item>
    <item>69m</item>
    <item>75m</item>
    <item>81m</item>
    <item>88m</item>
    <item>95m</item>
    <item>103m</item>
    <item>112m</item>
    <item>122m</item>
    <item>132m</item>
    <item>143m</item>
    <item>156m</item>
    <item>170m</item>
    <item>185m</item>
    <item>201m</item>
    <item>219m</item>
    <item>238m</item>
    <item>260m</item>
    <item>283m</item>
    <item>308m</item>
    <item>336m</item>
    <item>367m</item>
    <item>400m</item>
    <item>436m</item>
    <item>476m</item>
    <item>520m</item>
    <item>567m</item>
    <item>619m</item>
    <item>676m</item>
    <item>738m</item>
    <item>806m</item>
    <item>881m</item>
    <item>962m</item>
    <item>1.1s</item>
    <item>1.1s</item>
    <item>1.3s</item>
    <item>1.4s</item>
    <item>1.5s</item>
    <item>1.6s</item>
    <item>1.8s</item>
    <item>2.0s</item>
    <item>2.1s</item>
    <item>2.3s</item>
    <item>2.6s</item>
    <item>2.8s</item>
    <item>3.1s</item>
    <item>3.3s</item>
    <item>3.7s</item>
    <item>4.0s</item>
    <item>4.4s</item>
    <item>4.8s</item>
    <item>5.2s</item>
    <item>5.7s</item>
    <item>6.3s</item>
    <item>6.8s</item>
    <item>7.5s</item>
    <item>8.2s</item>
    <item>9.0s</item>
    <item>9.8s</item>
    <item>10.7s</item>
    <item>11.7s</item>
    <item>12.8s</item>
    <item>14.0s</item>
    <item>15.3s</item>
    <item>16.8s</item>
    <item>18.3s</item>
    <item>20.1s</item>
    <item>21.9s</item>
    <item>24.0s</item>
    <item>26.3s</item>
    <item>28.7s</item>
    <item>31.4s</item>
    <item>34.4s</item>
    <item>37.6s</item>
    <item>41.1s</item>
